[package]
name = "day16"
version = "0.0.0"
publish = false
edition = "2021"

[[bin]]
name = "day16"
path = "main.rs"

[dependencies]
anyhow = "1"
bit-vec = "0.6"
chumsky = "0.8"
indexmap = "1.9"
rayon = "1.6"
